<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DotNetExtras.Mail</AssemblyName>
    <RootNamespace>DotNetExtras.Mail</RootNamespace>
    <Version>1.0.8</Version>
    <Title>$(AssemblyName)</Title>
    <Authors>Alek Davis</Authors>
    <Description>A .NET Core library implementing mail template functionality based on the Razor syntax.</Description>
    <Copyright>© 2026 Alek Davis</Copyright>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageProjectUrl>https://alekdavis.github.io/dotnet-extras-mail</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/alekdavis/dotnet-extras-mail</RepositoryUrl>
    <PackageTags>.net;utilities;helpers;library;classes;tools;toolbox;mail;</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeSourceRevisionInInformationalVersion>False</IncludeSourceRevisionInInformationalVersion>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReleaseNotes>Have the Load method to return the message interface.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="RazorLight" Version="2.3.1" />
  </ItemGroup>

</Project>
